version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  generate: 
    aliases:
      - gen  
    desc: "Generate go-proto files"  
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I ../proto ./../proto/sso/*.proto --go_out=./../gen/go/ --go_opt=paths=source_relative --go-grpc_out=./../gen/go/ --go-grpc_opt=paths=source_relative